<!-- jQuery Min JS -->
<script src="web3_assets/js/jquery.min.js"></script>
<!-- Prpper JS -->
<script src="web3_assets/js/popper.min.js"></script>
<!-- Bootstrap Min JS -->
<script src="web3_assets/js/bootstrap.min.js"></script>
<!-- Jquery Magnific Popup Min Js -->
<script src="web3_assets/js/jquery.magnific-popup.min.js"></script>
<!-- Jquery Mixitup Min Js -->
<script src="web3_assets/js/jquery.mixitup.min.js"></script>
<!-- Waypoints Min Js -->
<script src="web3_assets/js/waypoints.min.js"></script>
<!-- Jquery CounterUp Min JS -->
<script src="web3_assets/js/jquery.counterup.min.js"></script>
<!-- Countdown -->
<script src="web3_assets/js/count-down.js"></script>
<!-- Swiper JS -->
<script src="web3_assets/js/swiper-bundle.min.js"></script>
<!-- Main JS -->
<script src="web3_assets/js/main.js"></script>
<!-- Custom JS -->
<script src="web3_assets/js/custom.js"></script>
