<footer class="footer-area bg-dark">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="single-footer-widget">
                    <h3>Services</h3>
                    <ul class="services-list">
                        <li><a href="#">NFT Assets</a></li>
                        <li><a href="#">Cryptocurrency</a></li>
                        <li><a href="#">Affiliations</a></li>
                        <li><a href="#">Blog</a></li>
                        <li><a href="#">Newsletter</a></li>
                    </ul>
                </div>
            </div>

            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="single-footer-widget">
                    <h3>Information</h3>
                    <ul class="usefull-links">
                        <li><a href="#">Sign Up</a></li>
                        <li><a href="#">NFT Dashboard</a></li>
                        <li><a href="#">Help Center</a></li>
                        <li><a href="#">About Us</a></li>
                    </ul>
                </div>
            </div>

            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="single-footer-widget">
                    <h3>Company</h3>
                    <ul class="usefull-links">
                        <li><a href="#">Terms of Use</a></li>
                        <li><a href="#">FAQ</a></li>
                        <li><a href="#">Contact Us</a></li>
                        <li><a href="#">Partnership</a></li>
                    </ul>
                </div>
            </div>

            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="single-footer-widget">
                    <div class="logo">
                        <a href="index.html"><img src="assets/img/logo.png"></a>
                    </div>
                    <p>Stay connected with us and let's know more about our NFT Market and more explorer us in this.</p>
                    <ul class="social-links">
                        <li><a href="#"><i class="icofont-facebook"></i></a></li>
                        <li><a href="#"><i class="icofont-twitter"></i></a></li>
                        <li><a href="#"><i class="icofont-instagram"></i></a></li>
                        <li><a href="#"><i class="icofont-linkedin"></i></a></li>
                        <li><a href="#"><i class="icofont-pinterest"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class="copyright-area">
        <div class="container">
            <div class="row" style="align-items: flex-end;">
                <div class="col-lg-4 col-md-6">
                    <ul>
                        <li><a href="#">Terms & Conditions</a></li>
                        <li><a href="#">Privacy Policy</a></li>
                    </ul>
                </div>

                <div class="col-lg-4 col-md-6 text-center">
                    <p>Copyright @2022 Todos os direitos reservados</p>
                </div>

                <div class="col-lg-4 col-md-6 text-right">
                    <p>Um produto&nbsp;&nbsp;<a href="#" target="_blank"><img src="assets/img/logo-mobi-white.png" style="vertical-align: baseline;" class="img-fluid"></a></p>
                </div>
            </div>
        </div>
    </div>
</footer>
