<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<!-- Favicon -->
<link rel="shortcut icon" href="favicon.png">

<!-- Bootstrap CSS -->
<link rel="stylesheet" href="web3_assets/css/bootstrap.min.css">
<!-- IcoFont Min CSS -->
<link rel="stylesheet" href="web3_assets/css/icofont.min.css">
<!-- Font Awesome CSS -->
<link rel="stylesheet" href="web3_assets/fonts/font-awesome/css/font-awesome.css">
<script src="https://kit.fontawesome.com/42003fc0f0.js" crossorigin="anonymous"></script>
<!-- Animate CSS -->
<link rel="stylesheet" href="web3_assets/css/animate.css">
<!-- Magnific Popup CSS -->
<link rel="stylesheet" href="web3_assets/css/magnific-popup.css">
<!-- Style CSS -->
<link rel="stylesheet" href="web3_assets/css/style.css">
<!-- Responsive CSS -->
<link rel="stylesheet" href="web3_assets/css/responsive.css">
<!-- Web Fonts -->
<link href="https://fonts.googleapis.com/css?family=Urbanist:300,300i,400,400i,700,700i" rel="stylesheet">
<!-- Swiper CSS -->
<link rel="stylesheet" href="web3_assets/css/swiper-bundle.min.css"/>
<!-- Custom CSS -->
<link rel="stylesheet" href="web3_assets/css/custom.css">

<title>IT'S NFT</title>
