<?php if ($this->pageCount) : ?>

    <nav>
        <ul class="pagination pagination-rounded justify-content-end">

            <!-- First page link -->
            <?php if (isset($this->previous)) : ?>
                <li class="page-item">
                    <a class="page-link"
                       href="<?php echo $this->url($this->route, ['action' => 'links', 'page' => $this->first]); ?>"
                       aria-label="<?= $this->translate('First page'); ?>"
                       title="<?= $this->translate('First page'); ?>"
                    >
                        <span aria-hidden="true"><?= $this->translate('First page'); ?></span>
                        <span class="sr-only"><?= $this->translate('First page'); ?></span>
                    </a>
                </li>
            <?php else : ?>
                <li class="page-item">
                    <a class="page-link"
                       href="javascript: void(0);"
                       aria-label="<?= $this->translate('First page'); ?>"
                       title="<?= $this->translate('First page'); ?>"
                    >
                        <span aria-hidden="true"><?= $this->translate('First page'); ?></span>
                        <span class="sr-only"><?= $this->translate('First page'); ?></span>
                    </a>
                </li>
            <?php endif; ?>

            <!-- Previous page link -->
            <?php if (isset($this->previous)) : ?>
                <li class="page-item">
                    <a class="page-link"
                       href="<?php echo $this->url($this->route, ['action' => 'links', 'page' => $this->previous]); ?>"
                       aria-label="<?= $this->translate('Previous'); ?>"
                       title="<?= $this->translate('Previous'); ?>"
                    >
                        <span aria-hidden="true">&larr;</span>
                        <span class="sr-only"><?= $this->translate('Previous'); ?></span>
                    </a>
                </li>
            <?php else : ?>
                <li class="page-item">
                    <a class="page-link"
                       href="javascript: void(0);"
                       aria-label="<?= $this->translate('Previous'); ?>"
                       title="<?= $this->translate('Previous'); ?>"
                    >
                        <span aria-hidden="true">&larr;</span>
                        <span class="sr-only"><?= $this->translate('Previous'); ?></span>
                    </a>
                </li>
            <?php endif; ?>

            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page) : ?>
                <?php if ($page != $this->current) : ?>
                    <li class="page-item">
                        <a class="page-link" href="<?= $this->url($this->route, ['action' => 'links', 'page' => $page]); ?>">
                            <?= $page; ?>
                        </a>
                    </li>
                <?php else : ?>
                    <li class="page-item active"><a class="page-link" href="javascript: void(0);"><?= $page; ?></a></li>
                <?php endif; ?>
            <?php endforeach; ?>

            <!-- Next page link -->
            <?php if (isset($this->next)) : ?>
                <li class="page-item">
                    <a class="page-link"
                       href="<?= $this->url($this->route, ['action' => 'links', 'page' => $this->next]); ?>"
                       aria-label="<?= $this->translate('Next page'); ?>"
                       title="<?= $this->translate('Next page'); ?>"
                    >
                        <span aria-hidden="true">&rarr;</span>
                        <span class="sr-only"><?= $this->translate('Next page'); ?></span>
                    </a>
                </li>
            <?php else : ?>
                <li class="page-item">
                    <a class="page-link"
                       href="javascript: void(0);"
                       aria-label="<?= $this->translate('Next page'); ?>"
                       title="<?= $this->translate('Next page'); ?>"
                    >
                        <span aria-hidden="true">&rarr;</span>
                        <span class="sr-only"><?= $this->translate('Next page'); ?></span>
                    </a>
                </li>
            <?php endif; ?>

            <!-- Last page link -->
            <?php if (isset($this->next)) : ?>
                <li class="page-item">
                    <a class="page-link"
                       href="<?= $this->url($this->route, ['action' => 'links', 'page' => $this->last]); ?>"
                       aria-label="<?= $this->translate('Last page'); ?>"
                       title="<?= $this->translate('Last page'); ?>"
                    >
                        <span aria-hidden="true"><?= $this->translate('Last page'); ?></span>
                        <span class="sr-only"><?= $this->translate('Last page'); ?></span>
                    </a>
                </li>
            <?php else : ?>
                <li class="page-item">
                    <a class="page-link"
                       href="javascript: void(0);"
                       aria-label="<?= $this->translate('Last page'); ?>"
                       title="<?= $this->translate('Last page'); ?>"
                    >
                        <span aria-hidden="true"><?= $this->translate('Last page'); ?></span>
                        <span class="sr-only"><?= $this->translate('Last page'); ?></span>
                    </a>
                </li>
            <?php endif; ?>
        </ul>
    </nav>

<?php endif;
