<div class="left-side-menu">
    <div class="slimscroll-menu">

        <a href="<?= $this->url('home'); ?>" class="logo text-center">
            <span class="logo-lg">
                <img src="/images/app-icone.png" alt="" height="166">
            </span>
            <span class="logo-sm">
                <img src="/images/app-icone.png" alt="" height="166">
            </span>
        </a>

        <ul class="metismenu side-nav">
            

            <li class="side-nav-title side-nav-item mt-1">
                <?= $this->translate('Administrativo'); ?>
            </li>
            <li class="side-nav-item">
                <a href="<?= $this->url('registers'); ?>" class="side-nav-link">
                    <i class="dripicons-archive"></i>
                    <span> PDV's </span>
                </a>
            </li>

            <li class="side-nav-item">
                <a href="<?= $this->url('categories'); ?>" class="side-nav-link">
                    <i class="dripicons-view-thumb"></i>
                    <span> Categorias </span>
                </a>
            </li>

            <li class="side-nav-item">
                <a href="<?= $this->url('types'); ?>" class="side-nav-link">
                    <i class="dripicons-network-3"></i>
                    <span> Tipos </span>
                </a>
            </li>

            <li class="side-nav-item">
                <a href="<?= $this->url('debits-admin'); ?>" class="side-nav-link">
                    <i class="dripicons-checklist"></i>
                    <span> Débitos </span>
                </a>
            </li>


            <li class="side-nav-item">
                <a href="<?= $this->url('user'); ?>" class="side-nav-link">
                    <i class="dripicons-user-group"></i>
                    <span> <?= $this->translate('Users'); ?> </span>
                </a>
            </li>

            <!---------------------------------------------------------------------->

            <li class="side-nav-title side-nav-item mt-1">
                <?= $this->translate('Relatórios'); ?>
            </li>
            <li class="side-nav-item">
                <a href="<?= $this->url('home'); ?>" class="side-nav-link">
                    <i class="dripicons-meter"></i>
                    <span> Dashboard </span>
                </a>
            </li>

            <li class="side-nav-item">
                <a href="<?= $this->url('transactions-admin'); ?>" class="side-nav-link">
                    <i class="dripicons-blog"></i>
                    <span> <?= $this->translate('Transações'); ?> </span>
                </a>
            </li>

            <li class="side-nav-item">
                <a href="<?= $this->url('debits'); ?>" class="side-nav-link">
                    <i class="dripicons-folder-open"></i>
                    <span> <?= $this->translate('Receber Dívidas'); ?> </span>
                </a>
            </li>

            <li class="side-nav-item">
                <a href="<?= $this->url('sales-admin'); ?>" class="side-nav-link">
                    <i class="dripicons-folder"></i>
                    <span> <?= $this->translate('Vendas'); ?> </span>
                </a>
            </li>
            
            <!-- 
            <li class="side-nav-item">
                <a href="javascript: void(0);" class="side-nav-link">
                    <i class="dripicons-monitor"></i>
                    <span> <?= $this->translate('PDVs'); ?> </span>
                    <span class="menu-arrow"></span>
                </a>
                <ul class="side-nav-second-level" aria-expanded="false">
                    
                    <li>
                        <a href="<?= $this->url('registers'); ?>">Lista PDV's</a>
                    </li>
                    <li>
                        <a href="<?= $this->url('debits-admin'); ?>">Dívidas</a>
                    </li>
                    <li>
                        <a href="<?= $this->url('categories'); ?>">Categorias</a>
                    </li>
                    <li>
                        <a href="<?= $this->url('types'); ?>">Tipos</a>
                    </li>

                </ul>
            </li>

            -->
        </ul>

        
        <div class="clearfix"></div>
    </div>
</div>
