<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle(\Application\Module::APPLICATION_NAME)
            ->setSeparator(' - ')
            ->setAutoEscape(false)
        ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->

        <?= $this->headLink()
            ->prependStylesheet($this->s3Url('/css/custom.css?' . date('YmdHi')))
            ->prependStylesheet($this->s3Url('/css/app.css'))
            ->prependStylesheet($this->s3Url('/css/bootstrap-datepicker3.min.css'))
            ->prependStylesheet('https://fonts.googleapis.com/icon?family=Material+Icons')
            ->prependStylesheet($this->s3Url('/css/icons.min.css'))
            ->prependStylesheet($this->s3Url('/css/vendor/jquery-jvectormap-1.2.2.css'))
            ->prependStylesheet($this->s3Url('/css/vendor/dataTables.bootstrap4.css'))
            ->prependStylesheet($this->s3Url('/css/vendor/responsive.bootstrap4.css'))
            ->prependStylesheet($this->s3Url('/css/vendor/buttons.bootstrap4.css'))
            ->prependStylesheet($this->s3Url('/css/vendor/select.bootstrap4.css'))
            ->prependStylesheet($this->s3Url('/vendors/busy-load/app.min.css'))
        ?>

        <link rel="apple-touch-icon" sizes="57x57" href="/assets/icons/apple-icon-57x57.png">
        <link rel="apple-touch-icon" sizes="60x60" href="/assets/icons/apple-icon-60x60.png">
        <link rel="apple-touch-icon" sizes="72x72" href="/assets/icons/apple-icon-72x72.png">
        <link rel="apple-touch-icon" sizes="76x76" href="/assets/icons/apple-icon-76x76.png">
        <link rel="apple-touch-icon" sizes="114x114" href="/assets/icons/apple-icon-114x114.png">
        <link rel="apple-touch-icon" sizes="120x120" href="/assets/icons/apple-icon-120x120.png">
        <link rel="apple-touch-icon" sizes="144x144" href="/assets/icons/apple-icon-144x144.png">
        <link rel="apple-touch-icon" sizes="152x152" href="/assets/icons/apple-icon-152x152.png">
        <link rel="apple-touch-icon" sizes="180x180" href="/assets/icons/apple-icon-180x180.png">
        <link rel="icon" type="image/png" sizes="192x192"  href="/assets/icons/android-icon-192x192.png">
        <link rel="icon" type="image/png" sizes="32x32" href="/assets/icons/favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="96x96" href="/assets/icons/favicon-96x96.png">
        <link rel="icon" type="image/png" sizes="16x16" href="/assets/icons/favicon-16x16.png">
        <link rel="manifest" href="/assets/icons/manifest.json">
        <meta name="msapplication-TileColor" content="#ffffff">
        <meta name="msapplication-TileImage" content="/assets/icons/ms-icon-144x144.png">
        <meta name="theme-color" content="#ffffff">
            
        <!-- Main Script -->
        <?= $this->headScript()
            ->prependFile($this->s3Url('/js/app.min.js'))
        ?>
        <script>
            $(document).ready(function () {
                let mesesCorrentes = [];
                let dataCorrentes = [];
                let mesesCorrentesDebt = [];
                let dataCorrentesDebt = [];
                let dataVendas = {};
                let dataDividas = {};
            });
        </script>
    </head>
    <body>

        <!-- Begin page -->
        <div class="wrapper">
            
            <?= $this->partial('partials/sidemenu' . $menuComplement . '.phtml'); ?>

            <!-- ============================================================== -->
            <!-- Start Page Content here -->
            <!-- ============================================================== -->

            <div class="content-page">
                <div class="loading"></div>
                <div class="content">
                    <?= $this->partial('partials/topbar.phtml'); ?>

                    <!-- Start Content-->
                    <div class="container-fluid">
                        <input type="hidden" id="stepSize" value="5000">
                        <?= $this->content ?>
                    </div>
                </div>

                <!-- Footer Start -->
                <footer class="footer">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-md-6">
                                <?php echo date('Y'); ?>  - mobiup.com.br
                            </div>
                            <div class="col-md-6">
                                <!--
                                <div class="text-md-right footer-links d-none d-md-block">
                                    <a href="javascript: void(0);">About</a>
                                    <a href="javascript: void(0);">Support</a>
                                    <a href="javascript: void(0);">Contact Us</a>
                                </div>
                                -->
                            </div>
                        </div>
                    </div>
                </footer>
                <!-- end Footer -->
            </div>
        </div>

        <?php //echo $this->partial('partials/right-sidebar.phtml'); ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->s3Url('/js/vendor/math.min.js'))
            ->prependFile($this->s3Url('/js/jquery.mask.min.js'))
            ->prependFile($this->s3Url('/js/bootstrap-datepicker.pt-BR.min.js'))
            ->prependFile($this->s3Url('/js/bootstrap-datepicker.min.js'))
            
            ->prependFile($this->s3Url('/js/admin/dashboard.js?' . date('YmdHi')))
            ->prependFile($this->s3Url('/js/admin/custom.js?' . date('YmdHi')))
            ->prependFile($this->s3Url('/js/vendor/jquery-jvectormap-world-mill-en.js'))
            ->prependFile($this->s3Url('/js/vendor/jquery-jvectormap-1.2.2.min.js'))

            ->prependFile($this->s3Url('/js/vendor/apexcharts.min.js'))
            ->prependFile($this->s3Url('/js/graphs.js'))
            ->prependFile($this->s3Url('/js/vendor/bootstrap-datepicker.pt-BR.min.js'))
            ->prependFile($this->s3Url('/js/vendor/bootstrap-datepicker.min.js'))

            ->prependFile($this->s3Url('/js/vendor/Chart.bundle.min.js'))
            ->appendFile($this->s3Url('/vendors/busy-load/app.min.js'))
            
        ?>

        <?= $this->inlineScript() ?>
        

    </body>
</html>
