<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle(\Application\Module::APPLICATION_NAME)
            ->setSeparator(' - ')
            ->setAutoEscape(false)
        ?>

<!--         $this->headMeta()-->
<!--           ->appendName('viewport', 'width=device-width, initial-scale=1.0')-->
<!--            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')-->

        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, shrink-to-fit=no">
        <!-- Le styles -->




    <link rel="stylesheet" href="<?= $this->s3Url('/css-pay/bootstrap.min.css'); ?>" />
    <link rel="stylesheet" href="<?= $this->s3Url('/css-pay/styles.css'); ?>" />
    <link rel="stylesheet" href="<?= $this->s3Url('/css-pay/card.css'); ?>" />
    <link rel="stylesheet" href="<?= $this->s3Url('/vendors/busy-load/app.min.css'); ?>">
    <link rel="apple-touch-icon" sizes="57x57" href="/assets/icons/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/assets/icons/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/assets/icons/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/assets/icons/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/assets/icons/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/assets/icons/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/assets/icons/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/assets/icons/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/assets/icons/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192"  href="/assets/icons/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/assets/icons/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/assets/icons/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/assets/icons/favicon-16x16.png">
    <link rel="manifest" href="/assets/icons/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/assets/icons/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">

    <!-- Main Script -->
    <?= $this->headScript()
        ->prependFile($this->s3Url('/js/vendor/sweet-alert.js'))
        ->prependFile($this->s3Url('/js/jquery.mask.min.js'))
        ->prependFile($this->s3Url('/js/vendor/jquery-3.4.1.min.js'))
    ?>
    </head>
    
    <body>
<!--        <header>-->
<!--            <img src=" $this->s3Url('/images/app-icone.png')" class="logo" />-->
<!--        </header>-->

        <!-- Start Content-->
<!--        <article class="container">-->
            <div class="loading"></div>
            <?= $this->partial('partials/flash-messages-site'); ?>
            <?= $this->content ?>
<!--        </article>-->
        
<!--        <br/><br/><br/><br/><br/>-->
<!--        <br/><br/><br/><br/><br/>-->
<!--        <br/><br/><br/><br/><br/>-->
<!--        <br/><br/><br/>-->
        <br/><br/><br/><br/><br/>
        <br/><br/><br/>
        <!-- Scripts -->
        <?= $this->inlineScript() ?>
    </body>
</html>
