<?php
$https = 'http://';
if (isset($_SERVER["HTTPS"]) && $_SERVER["HTTPS"] == "on") {
    $https = 'https://';
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>CONCESSÃO DE DIREITO REAL DE USO</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="<?=$https.$_SERVER['HTTP_HOST']?>/assets/css/styles.css" rel="stylesheet" />

    <script src="https://code.jquery.com/jquery-3.6.1.slim.min.js" integrity="sha256-w8CvhFs7iHNVUtnSP0YKEg00p9Ih13rlL9zGqvLdePA=" crossorigin="anonymous"></script>

    <script src="https://www.unpkg.com/web3@1.7.0/dist/web3.min.js"></script>
    <script type="text/javascript" src="https://unpkg.com/web3modal"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/evm-chains@0.2.0/dist/umd/index.min.js"></script>
    <script type="text/javascript" src="https://unpkg.com/@walletconnect/web3-provider"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js" integrity="sha512-pHVGpX7F/27yZ0ISY+VVjyULApbDlD0/X0rgGbTqCE7WFW5MezNTWG/dnhtbBuICzsd0WQPgpE4REBLv+UqChw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <link href="//cdn.jsdelivr.net/npm/@sweetalert2/theme-dark@3/dark.css" rel="stylesheet">
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@9/dist/sweetalert2.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/@toruslabs/torus-embed"></script>
    <script>
        let base = '<?=$https.$_SERVER['HTTP_HOST']?>/';
    </script>
</head>
<body>
<!-- Navigation-->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href="/">CONCESSÃO DE DIREITO REAL DE USO</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="/">Home</a></li>
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="/ends">Encerramento</a></li>
            </ul>
            <div class="header-dropdown-buttons text-md-right">
                <div class="btn-success btn-group position-relative connect-area">
                    <button class="hidden-md-down btn btn-default-transparent radius-50" onclick="javascript: $('#modalConnect').modal('show');"><i class="bi bi-wallet"></i> Conectar</button>
                </div>
                <div class="btn-group position-relative disconnect-area" style="display:none;">
                    <button class="btn-success hidden-md-down btn btn-default-transparent radius-50 connected"  data-toggle="dropdown" aria-expanded="true" aria-haspopup="true"><i class="bi bi-wallet"></i> 0x000...0000</button>
                    <div class="dropdown-menu dropdown-menu-right cart dropdown-animation" aria-labelledby="header-drop">
                        <a class="dropdown-item d-flex align-items-center justify-content-between font-weight-bold disconnect" href="javascript:void(0);" onclick="onDisconnect();">
                            Desconectar
                            <span><i class="bi bi-box-arrow-left"></i></span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</nav>

<div class="modal popup fade" id="modalConnect" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                <h2 class="text-center">Conectar</h2>
                <p class="text-center">Conecte com uma das carteiras disponíveis para mintar seu NFT ou participar do leilão.</p>
                <div class="wallet__options mt-3">

                    <div class="d-grid gap-2 col-6 mx-auto">
                        <button class="btn btn-primary" onclick="onConnect();" type="button">
                            Metamask <span><img src="<?=$https.$_SERVER['HTTP_HOST']?>/assets/img/metamask-alternative.png" alt="" width="18"></span>
                        </button>
                        <button class="btn btn-primary" onclick="javascript: $('#modalConnect').modal('hide')" type="button">Fechar</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<section class="py-5">
    <div class="container px-4 px-lg-5 mt-5">
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center row-nfts"></div>
    </div>
</section>
<!-- Footer-->
<footer class="py-5 bg-dark">
    <div class="container"><p class="m-0 text-center text-white">Copyright &copy; 2022</p></div>
</footer>
<!-- Bootstrap core JS-->
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
<!-- Core theme JS-->
<script src="<?=$https.$_SERVER['HTTP_HOST']?>/assets/js/scripts.js?t=<?=time()?>"></script>
<script>
    setTimeout(() => {
        dataInfoNfts();
    }, 500);
</script>
</body>
</html>
